### PR TITLE
prevent throwing TypeError on group events

### PR DESCRIPTION
**Pull request by markusduffek**
on group/meta events, a TypeError is throwing

### CODE REVIEW

**Comment by coreGreenberet** [comment]
In which scenario would groups be None? 
At the moment I'm thinking that it would make more sense to throw TypeError myself.

**Comment by markusduffek** [comment]
In my case, for every GROUP_CHANGED event. So, I'll investigate what's the problem at my side. ;-)

**Comment by sander76** [comment]
@markusduffek @coreGreenberet This seems to happen when a `GROUP_CHANGED` event occurs and the actual group is a `MetaGroup`. The `from_json` method of the `MetaGroup` has `groups` as an extra parameter. This isn't included inside the `GROUP_CHANGED` event and throws the TypeError.

So I am not sure whether this is a solution as groups will always be none when called from an event change. (But it could just be correct...)

**Comment by coreGreenberet** [comment]
could you please check if it is now working for you?

**Comment by sander76** [comment]
@coreGreenberet It throws an error. Can you see my comment on your code ?
https://github.com/coreGreenberet/homematicip-rest-api/pull/52

**Pull request closed without merging**
