### PR TITLE
Add channel state to OpenCollector8Module

### PR DESCRIPTION
**Pull request by mxworm**
Add channel state to OpenCollector8Module as `on_ch[]`

### CODE REVIEW

**Comment by coreGreenberet** [comment]
I don't think that a seperate array would be good in this case. If we start doing this here, than we would have to do it on all possible values in all device classes.

However I understand your need for printing the on state for all channels.

Could you please use a generic way in the Switch class?
e.g. count the SWITCH_CHANNELS and in __str__ -> if count = 1 -> like it is now, if count > 1 -> your version with a loop

**Comment by mxworm** [comment]
I tried hard to find a good solution to implement the multi channel device into the Switch class. But I'm manly afraid to destroy perfect working devices by adding something like "if count == 1: your code and  else the array code". What do you think about this implementation now?

**Comment by coreGreenberet** [comment]
what I still don't get is why you are overwriting "on" / creating a new array for it.
there is a self.functionalChannels array which holds all channels. So in the Switch case you could also use
self.functionalChannels[1].on

we can also discuss this in discord if you want.

**Comment by coreGreenberet** [comment]
do you still want to merge this PR or do you have some additional changes?

**Pull request closed without merging**
