### PR TITLE
Moved to API version 10 since version 8 is not supported anymore.

### PR DESCRIPTION
**Pull request by marcsowen**

### CODE REVIEW

**Comment by coreGreenberet** [comment]
thats strange, I'm still using version 8 and I don't have any issues at all.
could you check what your AP Version is? Mine is on
HmIP AccessPoint                              - Firmware: 1.2.2  - Available Firmware: None   UpdateState: UP_TO_DATE

**Comment by marcsowen** [comment]
Mine is also Version 1.2.2. But there is a version provided by the backend:

HmIP AccessPoint - Firmware: 1.2.2  - Available Firmware: 1.2.2  UpdateState: UP_TO_DATE

Maybe different accounts are on different API levels? I recently had to replace my Access Point after a failed firmware update. After that I had to re-connect all devices to the new access point.

**Comment by marcsowen** [comment]
By the way, this was the error I got with the master version (client version 8):

2017-05-24 11:58:57,949 - homematicip.home - ERROR - Could not get the current configuration. Error: CLIENT_VERSION_NOT_SUPPORTED

**Comment by coreGreenberet** [comment]
Could you try it again with API Version 8? Maybe there was an Error in the cloud. I've tested it also with apiversion 99 and even that was working. just nothing < 8

**Comment by marcsowen** [comment]
Strange. Now it works (again) using version 8. Maybe they are working on the backend?

**Comment by marcsowen** [comment]
After updating the iPhone App to version 1.7.0, I again get CLIENT_VERSION_NOT_SUPPORTED.

**Comment by coreGreenberet** [comment]
yes, I've fixed it already (you can ignore my email).
in the new version they've also implemented a new CLIENTAUTH header which was a little bit tricky

**Comment by marcsowen** [comment]
Thanks, latest master works perfectly!

**Pull request closed without merging**
