### PR TITLE
migrated to python3, still compatible with python2

### PR DESCRIPTION
**Pull request by mxworm**
Migration to python3 in oder to use your lib with Home Assistant

### CODE REVIEW

**Comment by coreGreenberet** [comment]
Thanks for your help here. My Problem with the merge is the range function :/
range(0,10) in py2 is the same as list(range(0,10)) in py3 and xrange in py2 is basically the same as range in py3

currently I'm using xrange just once in the code and on my machine the performance difference is just about 0.1usec we don't know where we might need it in the future.
I've also tested to use is with the import from builtins according to http://python-future.org/compatible_idioms.html but thats even worse from performance perspective :/

**Comment by coreGreenberet** [comment]
also your rewrite from __str__ doesn't work well in python 2.7
http://python-future.org/compatible_idioms.html#custom-str-methods

**Comment by mxworm** [comment]
OK, thanks for the info. I use python2.7 and python3.4 on my system and have tried both versions with my updates... Does this mean only a "if sys.version_info >= (3, 0):" can really help? Are you anyhow interested to be also python3 compatible?

Ciao Mattias

**Comment by coreGreenberet** [comment]
I don't think  that we have to check the version. Just the thing with the decorator.

To be honest I wound have used python3, but then I've checked which one gets used more in the field and python 2.7 got used way too much more.
But yeah if we could be compatible with both that won't be bad at all :)

**Pull request closed without merging**
