### PR TITLE
Add setControlMode function to HeatingGroup

### PR DESCRIPTION
**Pull request by mxworm**
Add setControlMode to switch between AUTOMATIC AND MANUAL mode.

### CODE REVIEW

**Comment by mxworm** [comment]
Should I revert the auto formatting?

**Comment by coreGreenberet** [comment]
The Auto formatting didn't do any harm here so you could let it stay. 
However could you please create an enum for the parameter instead of the string?

**Comment by mxworm** [comment]
Hey, what do you think about a function which controls the different states of the device as it has server different modes distributed over many functions?

set_mode(mode = PROFILE1, PROFILE2, MANUAL, BOOST):
  set_control_mode(....)
  set_boost(....)
  set_active_profile(.....) 
  and ECO mode

What do you think?

**Comment by coreGreenberet** [comment]
@mxworm I'm not sure to behonest about this, but I'm open for everything. I guess it is time to create a discord Server for discussions like this.

**Pull request merged**
