### PR TITLE
Make FakeCloudServer available for HA testing.

### PR DESCRIPTION
**Pull request by SukramJ**
Hi @coreGreenberet,

i have been searching for a possibility to enable testing of devices in HomeAssitant without owning them. Most of what i needed is already there in your lib, but hidden under test. 
GREAT WORK.

Thats why i did the following refactoring:
- Move FakeCloudServer and associated files to the new root path homematicip_demo. So they are available in the pypi package.
- enable FakeCloudServer to work with an external delivered home.json, so that tests i HA do not heaviliy depend on your own home.json.
- fix tests. mainly related to the new structure and some labels.

I tried to move only the minimum required amount of code to the new structure. 
I hope you agree with my changes.

BR

### CODE REVIEW

**Comment by coreGreenberet** [comment]
looks good for me

**Comment by coreGreenberet** [comment]
But be aware, that this isn't a fully functional server. 

E.g. deleteGroup will not remove the group from all of the channels in the devices.

**Comment by SukramJ** [comment]
Great. Do you have plans for a new release?

**Comment by SukramJ** [comment]
I know, i check every function i need and come back with feedback.

**Comment by coreGreenberet** [comment]
> Great. Do you have plans for a new release?

Well there are currently 2 open issues (#190 & #202) , which I would like to resolve before I create a new release

**Comment by coreGreenberet** [comment]
Release is on the way

**Comment by SukramJ** [comment]
Something went wrong.
I thought homematicip_demo is also included in the pypi package

**Comment by SukramJ** [comment]
Any idea?

**Comment by coreGreenberet** [comment]
ah the *_demo is missing an __init__.py
thats why it didn't got included while building the package

**Comment by SukramJ** [comment]
Ahhh. Thanks.
An empty init.py is ?

**Comment by steckenpferd** [comment]
@coreGreenberet @SukramJ  - wie genau funktioniert das neue Demo Paket - könnte man noch auf der Start Seite eine kurze Info - HowTo - hinzufügen?

**Comment by SukramJ** [comment]
>@coreGreenberet @SukramJ  - wie genau funktioniert das neue Demo Paket - könnte man noch auf der Start Seite eine kurze Info - HowTo - hinzufügen?

@steckenpferd Ich denke das macht aktuell noch keinen Sinn.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
