### PR TITLE
Fix enum backward compatitibility py34

### PR DESCRIPTION
**Pull request by mxworm**
Hi, I bumped into a backward compatibility issue with enum for py34 which homeassistent is asking for. 

- Would it be OK for you to change to `aenum`?
https://codereview.stackexchange.com/questions/177309/reimplementing-pythons-enum-auto-for-compatibility

- The windowState is sometime `None` for me with breaks the from_json function.
- Please, can you create a release with this fixes?

Thanks Mattias

### CODE REVIEW

**Comment by sander76** [comment]
@mxworm HomeAssistant is to drop py34 support? Or haven't they already ?

**Comment by mxworm** [comment]
Hi Sander, actualy HomeAssistant is checking python 3.4 in ther Travis CI . I don't know if they are going to drop py3.4, but at the moment I need to fullfill this requirment :-)

**Comment by sander76** [comment]
@mxworm That sucks. I'll have a shot at asking balloob whether python 3.4 will continue to be supported.

**Comment by sander76** [comment]
@mxworm update your repo. Py34 has already been dropped

**Comment by mxworm** [comment]
My proposal would be just to switch from `enum` to `aenum` which is backward compatible.

**Comment by coreGreenberet** [comment]
I've bist made a Quick check yet, but aenum doesn't have support for providing the name as value (or I didn't see it)

**Comment by mxworm** [comment]
You mean the auto() feature? If yes, please have a look to the link in the first comment....

**Comment by coreGreenberet** [comment]
Yes, but I've implemented a way to use auto so that the value is just the variable name as a string. This isn't working with aenum

**Comment by sander76** [comment]
@mxworm But if your build is not failing anymore, why switch to aemum ?
Also: the HMIP aio implementation does not support py3.4.

**Comment by mxworm** [comment]
- I would like to switch to aenum which has the auto() function also for py34
- actually I pass the py34 tests :-) widthout the enum changes in the lib

Ciao Mattias

**Comment by coreGreenberet** [comment]
could you also please add the aenum to the requirements.txt?
the tests are currently not passing

**Comment by mxworm** [comment]
Sorry, I missed a few comments from you guys.... I didn't want to be show up as a ignorant. Sorry!

I don't have an env. with py34 :-\ and I don't want to install py34..... how to proceed?

**Comment by sander76** [comment]
@mxworm No worries, but what do you mean ?

**Comment by mxworm** [comment]
The question is if `aenum` and the `auto()` function is working in py34 or not?

**Comment by sander76** [comment]
@mxworm But again, you request this for compatibility with HomeAssistant testing. But I checked and HASS already has dropped testing for 3.4.

Have a look here for a arbitrary PR on hass:
https://travis-ci.org/home-assistant/home-assistant/builds/403549440?utm_source=github_status&utm_medium=notification

No 3.4
So why relying on an external lib when it is not needed anymore ?

**Comment by mxworm** [comment]
Ohhhh, it's py35.... this is too much for my brain. I was relay convinced its an py34 issue.

https://travis-ci.org/home-assistant/home-assistant/builds/403212492?utm_source=github_status&utm_medium=notification

**Comment by sander76** [comment]
Time for vacation, swimming pool and a beer ;-)

But still. The `auto` is not supported in 3.5.3 either. But I feel 3.5.3 should be supported by HMIP. @coreGreenberet  what do you think ?

**Comment by mxworm** [comment]
OK, now we have moved the issue from (wrong) v3.4 to v3.5.3 :-/ ... and the beer would be a really good idea.

**Comment by sander76** [comment]
@mxworm aenum supports `auto` ? If so, we're good aren't we ?

**Comment by mxworm** [comment]
aenum supports `auto`: yes.

**Comment by coreGreenberet** [comment]
I don't have python 3.5 installed.
Could you please check if this is working?

**Comment by mxworm** [comment]
I will try to setup a virtual env. for py35 tomorrow :-) Thanks for the from_str method.
Ciao Mattias

**Comment by mxworm** [comment]
Seems to work fine - can you make a new release, please?

**Comment by coreGreenberet** [comment]
I will create a new tag as soon as I've finished & merged the functional_homes branch.
this shouldn't take too much time.

**Pull request merged**
